### ISSUE TITLE
Axios V1 and Jest do not work along nicely

### ISSUE THREAD

**Issue by TimQuist** [42BV/mad-spring-connect#65]
@gidomanders 

@botenbreuk had to add the following to the package.json in order for jest tests to run successfully.
From issue: https://github.com/axios/axios/issues/5140

Had to add:
```json
"jest": {
    "transformIgnorePatterns": ["node_modules/(?!(axios))"]
}
```

Maybe it is good to add this to the README.md or release notes so others will be aware of this as well?

Error:
```
FAIL  src/ui/Page/EnvBanner/EnvBanner.test.tsx
  ● Test suite failed to run

    Jest encountered an unexpected token

    Jest failed to parse a file. This happens e.g. when your code or its dependencies use non-standard JavaScript syntax, or when Jest is not configured to support such syntax.

    Out of the box Jest supports Babel, which will be used to transform your files into valid JS based on your Babel configuration.

    By default "node_modules" folder is ignored by transformers.

    Here's what you can do:
     • If you are trying to use ECMAScript Modules, see https://jestjs.io/docs/ecmascript-modules for how to enable it.
     • If you are trying to use TypeScript, see https://jestjs.io/docs/getting-started#using-typescript
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/configuration
    For information about custom transformations, see:
    https://jestjs.io/docs/code-transformation

    Details:

    /node_modules/axios/index.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,jest){import axios from './lib/axios.js';
                                                                                      ^^^^^^

    SyntaxError: Cannot use import statement outside a module

      at Runtime.createScriptFromCode (node_modules/jest-runtime/build/index.js:1728:14)
      at Object.<anonymous> (node_modules/@42.nl/spring-connect/lib/config.js:7:33)
```

**Comment by gidomanders** [comment]
Updating to Axios 1.1.3 solved the problem
